name: PHP

on: [push]

jobs:
  run:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: ["8.4", "8.5"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Validate Composer
        run: composer validate
      - name: Install Composer Deps
        run: composer install
      - name: PHPStan
        run: composer stan
      - name: Code Style
        run: composer format -- --dry-run --diff
      - name: Run Tests
        run: composer test
